### DISCUSSION TITLE
Elastalert not sending email

### DISCUSSION THREAD

**Discussion by mksquire66** [cisagov/LME#659] [FAQ]
I've configured the config.yaml file in the /opt/lme/config/elastalert2 directory and I'm not getting emails....   I want an email for any alert that triggers.  My config.yaml file is below - redacted some info.....     run_every:
  minutes: 1

buffer_time:
  minutes: 15

writeback_index: elastalert_status

log_file: /var/log/elastalert.log

alert_time_limit:
  days: 2

es_host: lme-elasticsearch
es_port: 9200
start_time: "now"
es_username: "elastic"
es_password: "my password is here"
use_ssl: true
verify_certs: false

smtp_host: internalsmtp.serverIsHere.org
smtp_port: 25
from_addr: "elastalert2@mycompany.org"
email: "myemail@mycompany.org"
smtp_auth_file: /opt/lme/config/elastalert2/smtp_auth.yml

#exists in the container
rules_folder: /opt/elastalert/rules

**Comment by aarz-snl** [comment]
Do your rules have this configuration in them at least?

```
alert:
  - email
```


You may be able to use config.yaml to host your stmpconfig /creds etc for all rules -- but your RULES may still need to be configured with the email alert configuration

Full example:

config.yaml


```

run_every:
  minutes: 1

buffer_time:
  minutes: 15

writeback_index: elastalert_status

log_file: /var/log/elastalert.log

alert_time_limit:
  days: 2

es_host: lme-elasticsearch
es_port: 9200
start_time: "now"
es_username: "elastic"
es_password: "your_actual_password_here"
use_ssl: true
verify_certs: false

rules_folder: /opt/elastalert/rules

smtp_host: internalsmtp.serverIsHere.org
smtp_port: 25
from_addr: "elastalert2@mycompany.org"
email: "destination_email@mycompany.org"
smtp_auth_file: /opt/lme/config/elastalert2/smtp_auth.yml
```

creds file:

```
user: "smtp-username"
password: "smtp-password"
```

example rule showing email configuration:

```
name: Simple Test Rule
type: any

index: my-index-*

filter:
- query:
    query_string:
      query: "*"

alert:
  - email
```


how to use test in container (enter the container)
```
sudo -i podman exec -it lme-elastalert2 bash
```


run test script:
```
elastalert-test-rule /opt/elastalert/rules/alert-name.yaml
```

 - i do recommend using yaml instead of yml
docs state:

```
Every file that ends in .yaml in the rules_folder will be run by default. The following configuration settings are common to all types of rules.
```

**Comment by mksquire66** [comment]
I don't have rules in the rules folder other than the ones that were there by default.  I was trying to avoid having to create a file for every rule that I've enabled and want to get alerted on (I just want an email for all alerts).  Am I mis-understanding what you're suggesting?   I did just modify the example-email-rule.yml file and added alert: 
  - email

**Comment by aarz-snl** [comment]
Yes, you may be misunderstanding -- when you say rules that you've enabled...what rules?

**Comment by mksquire66** [comment]
The rules in the web interface under "Security"

**Comment by aarz-snl** [comment]
So those are separate from elastalert... those will alert in kibana but they wont do anyting with email/slack/etc unless you use elastalert. 

Something i've been experimenting with is this -- tailored to your use case this may be a good test:

add this to the elastalert rules file at /opt/lme/config/elastalert2/rules

```
# /opt/lme/config/elastalert2/rules/rollup_kibana_alerts.yaml

name: Rollup Kibana Native Security Alerts
type: any
index: .alerts-security.alerts-*

filter:
  - range:
      "@timestamp":
        gte: "now-5m"
  - query_string:
      query: "kibana.alert.rule.name:*"

realert:
  minutes: 0

aggregation:
  minutes: 0

alert:
  - email

alert_text_type: alert_text_only
alert_text: |
  🚨 New Security Alert 🚨
  Severity: {0}
  Host: {1}
  Rule: {2}
  User: {3}
  Action: {4}

alert_text_args:
  - kibana.alert.severity
  - host.name
  - kibana.alert.rule.name
  - user.name
  - event.action
```

**Reply by mksquire66** [reply]
sorry - feeling a little dumb here....   Your first line seems contradictory - "So those are separate from elastalert... those will alert in kibana but they wont do anyting with email/slack/etc unless you use elastalert."    I thought I was trying to use elastalert.?  

Also - the bottom section under alert_text_args:  I put:   
alert_text_args:
  - kibana.alert.severity = "high"
  - host.name = "mysmtpserver.mycompany.org"
  - kibana.alert.rule.name = "Hidden User created"
  - user.name = "elastic@mycompany.org"
  - event.action = "login"
  
Is this correct?

**Reply by mksquire66** [reply]
I see the alert in Kibana - no email

**Reply by HopperShell** [reply]
Those will be args that get populated from the log that comes in. 

You don’t have to hard set anything. Just exactly as I provided it 

elastalert2 is a separate tool designed to monitor elasticsearch indexes and alert when a search is detected. Kibana alerts are built into kibana. They aren’t related at all. 

So you have to do 1 of 2 things. Either create your own elastalert rules (using the example template you see provided  you create rules for each scenario of your choice) 

or you monitor the index of the kibana alerts with elast alert and alert for anything detected. I hope that makes sense. I can give better explanation when I’m back at a computer

**Comment by HopperShell** [comment]
These right here

alert_text_args:
  - kibana.alert.severity
  - host.name
  - kibana.alert.rule.name
  - user.name
  - event.action
  
  are fields in the json from each alert 

so every alert has the field kibana.alert.severity field and it will be low, medium, high, or critical. We use an argument here to say get the severity and then add it to the alert 

so your email will start with 

severity: high or low or critical - whatever that single alert is 

does the same for each of those args 

you may have broken the rule by adding the = part to the end of each

**Comment by aarz-snl** [comment]
I got this working for me doing the following:

created a rule at the following location with the following configuration:

```
# /opt/lme/config/elastalert2/rules/rollup_kibana_alerts.yaml
name: Rollup Kibana Native Security Alerts
type: any
index: .alerts-security.alerts-*
filter:
  - range:
      "@timestamp":
        gte: "now-5m"
  - query_string:
      query: "kibana.alert.rule.name:*"
realert:
  minutes: 0
aggregation:
  minutes: 0
alert:
  - email
alert_text_type: alert_text_only
alert_text: |
  🚨 New Security Alert 🚨
  Severity: {0}
  Host: {1}
  Rule: {2}
  User: {3}
  Action: {4}
alert_text_args:
  - kibana.alert.severity
  - host.name
  - kibana.alert.rule.name
  - user.name
  - event.action
email:
  - "myemail@gmail.com"
smtp_host: "smtp.gmail.com"
smtp_port: 465
smtp_ssl: true
from_addr: "elastalert@elastalert.com"
smtp_auth_file: /opt/elastalert/misc/smtp_auth.yml
```

created authentication file at the following location:

```
# /opt/lme/config/elastalert2/misc/smtp_auth.yml
user: "email@gmail.com"
password: "passcode"
```

My config.yaml

```
run_every:
  minutes: 5

buffer_time:
  minutes: 15

writeback_index: elastalert_status

alert_time_limit:
  days: 2

es_host: lme-elasticsearch
es_port: 9200
use_ssl: true
verify_certs: false
ssl_show_warn: false

#exists in the container
rules_folder: /opt/elastalert/rules
```

restarted elastalert verify its online properly

```
sudo systemctl restart lme-elastalert.service
```
 
logs:

```
sudo -i podman logs -f lme-elastalert2
```

You may see warnings about http -- this is fine its just private docker network communications

if its up and running you can force the rule to run:

enter the container:

```
sudo -i podman exec -it lme-elastalert2 bash
```

Run elastalert rule:


```
elastalert --verbose --config /opt/elastalert/config.yaml --rule /opt/elastalert/rules/rollup_kibana_alerts.yml
```

verify in kibana you actually have an alert generated in the last 5 minutes... if not trigger one then run the command above. Check email

**Comment by aarz-snl** [comment]
updated location of smtp_auth.yml 

on host machine it must go here:

/opt/lme/config/elastalert2/misc/smtp_auth.yml

In this example


Just to clarify how this works.. we have a mount that takes 

/opt/lme/config/elastalert2 on the HOST machine and mounts it to /opt/elastalert in the container. 

so when you see references to /opt/elastalert in configuration files thats basically a function thats existing INSIDE the container -- but its actually mounted on the host machine to /opt/lme/config/elastalert2

**Comment by mksquire66** [comment]
Thanks so much for sharing these configs, etc. that you got working!  I copied what you have above and plugged it into my environment and get to the point of trying to enter the container and had issues.  The container keeps dropping and restarting every 2-3 seconds so doesn't stay up long enough to get into it.  I had this happen when trying to do the configuration based on documentation initially too, so I'm working through which line is causing me issues.  I'll post again when I have a better update.

**Reply by HopperShell** [reply]
this basically means theres a config or rule somewhere thats improperly configured. Id remove anything that ISN"T the config that we have discussed here. So, the config.yaml and the one single rule above

**Comment by cisspUser01** [comment]
If you configured everything in ElastAlert2 correctly and still have elastalert2 service dropping every 2-3 seconds. make sure you didnt change the default password. that's what happened to me. after I put back the elastic user default password. All alerts started to work.

**Reply by HopperShell** [reply]
Yes... it's built into the elastalert configuration to get access to elastic search it has to use the username and password. 

We still need to upgrade our password management script so it makes it easier to update passwords

**Comment by mksquire66** [comment]
Awesome!  I finally got it working with a few small tweaks...!   First with the 2-3 second restart with the elastalert service:  When I copy and pasted - it didn't paste quite right.  The line with the bomb icons didn't paste at all and the Severity line was indented a little more to the right.  After changing those 2 lines - the container stayed up.  :)  
alert_text: |
  🚨 New Security Alert 🚨
  Severity: {0}
  Host: {1}
  Rule: {2}
  User: {3}
  Action: {4}

I had to work through some issues with our smtp server (but got errors that indicated what was wrong) and now my mailbox is blowing up with alerts!  :). Thanks so much for your help!!!

**Reply by aarz-snl** [reply]
NP... now since we did it this way all you have to do is go into kibana -> security -> rules and turn off the noisy ones that are full of false positives. Or manually adjust the search they do if its just ONE thing causing hundreds of alerts

**Reply by cisspUser01** [reply]
are there any recommendation on what alerts to enable?
Thank you,

**Reply by aarz-snl** [reply]
Not really -- just up to each individually to decide what is important to monitor. Ie. if you're monitoring for specific threat actors -- then use the mitre attack tags to turn on alerts that are tied to those APTs. 

You could also just turn on critical and high only and see how that goes. 

There's also probably something that can be done with elastalert2 where it detects the field and if its critical or high it will be sent to your email. And if its not it doesn't. however, its still logged in kibana -- so if you have to map an incident out that still exists

Something like this:


```
name: Filtered Kibana Alerts
type: any
index: .alerts-security.alerts-*

filter:
  - range:
      "@timestamp":
        gte: "now-5m"
  - query_string:
      query: "kibana.alert.rule.name:*"
  - terms:
      kibana.alert.severity: ["high", "critical"]  # only these will trigger

realert:
  minutes: 0

aggregation:
  minutes: 0

alert:
  - "slack"

slack_webhook_url: "https://hooks.slack.com/services/..."
slack_username_override: "Alert Bot"
slack_icon_emoji_override: ":rotating_light:"

alert_text_type: alert_text_only
alert_text: |
  🚨 *New Security Alert*
  *Severity*: {0}
  *Rule*: {1}
  *User*: {2}
  *Action*: {3}

alert_text_args:
  - kibana.alert.severity
  - kibana.alert.rule.name
  - user.name
  - kibana.alert.action

```

Now those alerts will always live in kibana so you dont actually have to turn them off -- but they wont be sent to your slack this scenario 


Using filters and queries in your elastalert rule can trim this down as far as you want to any scenario.
