### ISSUE TITLE
POC - Sigma-to-ElastAlert Convesion - Generating ElastAlert rules

### ISSUE THREAD

**Issue by NVivero** [cisagov/LME#650]

**Comment by aarz-snl** [comment]
https://mitreattack-python.readthedocs.io/en/latest/mitre_attack_data/mitre_attack_data.html

**Comment by tylmorr-snl** [comment]
Continuing to convert Sigma rules to ElastAlert

**Comment by tylmorr-snl** [comment]
We have a working script that converts sigma rules to ElastAlert. Validation testing this script.

**Comment by tylmorr-snl** [comment]
Have ElastAlert monitor index that houses alerts from within Kibana and send notifications. We can add sigma rule alerts to this index.

**Comment by aarz-snl** [comment]
Proof of concept here proved -- but with a shift to make this much cleaner. 

You can monitor the kibana alerts index using a rule like this:

```
name: Rollup Kibana Native Security Alerts
type: any
index: .alerts-security.alerts-*
filter:
  - range:
      "@timestamp":
        gte: "now-5m"
  - query_string:
      query: "kibana.alert.rule.name:*"
realert:
  minutes: 0
aggregation:
  minutes: 0

# Import the Slack alert configuration
import: slack_alert
```


You can always build more alerts as needed - but what this does is allow you to utilize the hundreds of alerts that already come with kibana. 

in this scenario every 5 minutes the rule will check if any alerts have happened in the last 5 minutes. It will then send that information to the endpoint of your choice. If its multiple alerts they will all be rolled up into one report. This is ALL you have to configure in elastalert. All other configuration would be performed in kibana -> security -> rules
